import { Toaster } from '@/shared/ui/sonner'
import { Metadata } from 'next'
import { Geist } from 'next/font/google'

import Header from '../_layout/basic/header'
import { ThemeProvider } from '../_providers/theme-provider'
import '../globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} antialiased overflow-hidden`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header isAuth />
                    <main className="min-h-svh -mt-[88px] flex flex-col items-center justify-center gap-6 bg-background">
                        {children}
                    </main>
                    <Toaster richColors />
                </ThemeProvider>
            </body>
        </html>
    )
}
