import { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Geist } from 'next/font/google'

import { FooterSection } from '../_layout/basic/footer'
import Header from '../_layout/basic/header'
import { NextAuthProvider } from '../_providers/next-auth-provider'
import '../globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} antialiased overflow-x-hidden`}>
                <NextAuthProvider>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <Header />
                        <main className="flex flex-col mx-auto lg:max-w-screen-lg py-20 gap-20 md:gap-24 lg:gap-28">
                            {children}
                        </main>
                        <FooterSection />
                    </ThemeProvider>
                </NextAuthProvider>
            </body>
        </html>
    )
}
