import { SidebarInset, SidebarProvider } from '@/shared/ui/sidebar'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { redirect } from 'next/navigation'

import AppSidebar from '../_layout/dashboard/app-sidebar'
import Header from '../_layout/dashboard/header'
import { ThemeProvider } from '../_providers/theme-provider'
import '../globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} antialiased overflow-hidden`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <SidebarProvider defaultOpen>
                        <AppSidebar />
                        <SidebarInset>
                            <Header />
                            <main className="min-h-svh flex flex-col items-center justify-center gap-6 bg-background">
                                {children}
                            </main>
                        </SidebarInset>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
