import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "../_providers/theme-provider";
import { NextAuthProvider } from "../_providers/next-auth-provider";
import "../globals.css";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} antialiased overflow-hidden`}>
                <NextAuthProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <aside className="w-[20%] h-[80] border-r border-r-primary rounded-t-2xl roounded-b-2x">
                        sd
                        </aside>
                        <main className="min-h-svh flex flex-col items-center justify-center gap-6 bg-background">
                            {children}
                        </main>
                    </ThemeProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
